
name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64 #linux/arm/v6
  repo: hbdk/prty-fast

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: store latest_tag tag
        id: latest_tag
        run: |
          tag_name=$(cat $GITHUB_EVENT_PATH | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')
          echo ::set-output name=latest_tag::$([[ ! -z "$tag_name" ]] && echo "latest" || echo "dev")

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{env.platforms}}
          push: true
          tags: |
            ghcr.io/${{ env.repo }}:${{ steps.latest_tag.outputs.latest_tag }}

