
name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64 #linux/arm/v6
  repo: hbdk/prty-fast

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get tags
        run: |
          ref=${{github.ref}}
          branch_name=$(echo ${ref##*/} | sed 's/[^a-z0-9_.-]//g' | cut -c 1-128)
          if [[ $branch_name == "main" ]]; then
            latest_tag="latest"
          else
            latest_tag="dev"
          fi
          echo $branch_name
          echo $latest_tag
          echo "BRANCH_TAG=$branch_name" >> $GITHUB_ENV
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{env.platforms}}
          push: true
          tags: |
            ghcr.io/${{ env.repo }}:${{ env.BRANCH_TAG }}
            ghcr.io/${{ env.repo }}:${{ env.LATEST_TAG }}

